--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t dvohra/node-server ."
      - "docker tag dvohra/node-server:latest dvohra/node-server:latest"
  post_build: 
    commands: 
  pre_build: 
    commands: 
version: 0.1
